= Kritische Entscheidungen

Benutzte Version: *SQLite version 3.30.1*

. *Fremdschluessel:*
.. auf COLLATE NOCASE verzichtet, weil es ja schon in der Ursprungstabelle aufgefuehrt ist.
.. Aus der Formulierung "FOREIGN KEY (...) REFERENCES ...(...)" wurde nur "REFERENCES", da laut Christians Mail die beiden Operatoren synonym sind.
.. Alle Fremdschluessel wurden entgegen der rm_min.pdf nochmal umbenannt, weil IntelliJ mit dem Punkt nicht klarkam. Jetzt Underscore statt Punkt. Nils meinte in der Sprechstunde, dass so etwas nicht nochmal im RM umbenannt werden muss.

. *Suchanfragen:*
.. Generell habe ich immer die Mailadresse und einen (Kuenstler-)Namen ausgegeben.
.. Anfrage 2: Falls es irgendwann zwei Besucher in der DB geben sollte, die denselben Betrag fuer Tickets ausgegeben haben, dann werden auf diese Weise auch beide gelistet. Aus diesem Grund wurde hier seqnum verwendet.

. *Sonstiges:*
.. Aufgrund der Namensbindung kann ein Besucher nur ein Festival-Ticket besitzen. Die Verwendung von UNIQUE anstelle eines Triggers wurde in der Sprechstunde am letzten Freitag vorgeschlagen.
.. Da Veranstalter nicht mit sich selbst kooperieren koennen, ist in Zeile 206 der folgende Check verwendet worden:
----
CHECK (Veranstalter_User_Mailadresse1 != Veranstalter_User_Mailadresse2)
----
